### ISSUE TITLE
Add virus scanners to the Apio builder workflows

### ISSUE THREAD

**Issue by zapta** [FPGAwars/apio#652]
This applies to builder workflows that deal with binaries (packages such as oss-cad-suite and apio installers builders). Add to the workflow scanning of the generated package for viruses.

ChatGpt suggests something along these lines:
```
jobs:
  virus-scan:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # --------------------
      # Install ClamAV (Linux)
      # --------------------
      - name: Install ClamAV on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav
          sudo freshclam

      # --------------------
      # Install ClamAV (macOS)
      # --------------------
      - name: Install ClamAV on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install clamav
          mkdir -p /usr/local/var/lib/clamav
          freshclam --datadir=/usr/local/var/lib/clamav

      # --------------------
      # Install ClamAV (Windows)
      # --------------------
      - name: Install ClamAV on Windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install clamav --yes
          & 'C:\Program Files\ClamAV\freshclam.exe'

      # --------------------
      # Virus Scan
      # --------------------
      - name: Scan `_packages` for viruses
        run: |
          clamscan -r --infected --bell --quiet _packages

      # Optional: Fail build if infected
      # Remove this block if you prefer non-blocking scan results
      - name: Enforce clean scan
        run: |
          clamscan -r --infected _packages || exit 1
```
